"use client";

import { ProductHero } from "../components/ProductHero";
import { StatementCards } from "../components/StatementCards";
import { ResultCards } from "../components/ResultCards";
import { ProductFAQ } from "../components/ProductFAQ";

export default function DashboardsPage() {
  const heroContent = {
    badge: {
      en: "ONE SOURCE PLATFORM",
      es: "PLATAFORMA ÚNICA"
    },
    titlePart1: {
      en: "Customizable dashboards",
      es: "Dashboards personalizables"
    },
    titlePart2: {
      en: "to visualize, understand and manage your entire ecommerce ecosystem in one place",
      es: "para visualizar, entender y gestionar todo tu ecosistema de ecommerce en un solo lugar"
    },
    subtitle: {
      en: "Get a complete view of your business performance with dashboards designed to centralize key information, display real-time indicators and help you make quick and precise decisions. Everything adapted to your operation, your objectives and the way your team works.",
      es: "Obtén una visión completa del rendimiento de tu negocio con tableros diseñados para centralizar información clave, mostrar indicadores en tiempo real y ayudarte a tomar decisiones rápidas y precisas. Todo adaptado a tu operación, tus objetivos y la forma en que tu equipo trabaja."
    }
  };

  const statements = [
    {
      title: {
        en: "Information from your entire ecosystem in a single panel",
        es: "Información de todo tu ecosistema en un solo panel"
      },
      description: {
        en: "Unify data from your website, inventories, sales, payments, digital advertising, CRM, ERP and more to have a clear and complete view of the real state of your business.",
        es: "Unifica datos de tu sitio web, inventarios, ventas, pagos, pauta digital, CRM, ERP y más para tener una visión clara y completa del estado real de tu negocio."
      }
    },
    {
      title: {
        en: "Customizable dashboards according to your operation",
        es: "Dashboards personalizables según tu operación"
      },
      description: {
        en: "Choose which metrics are relevant for your team, organize cards, create specific views and monitor what really matters.",
        es: "Elige qué métricas son relevantes para tu equipo, organiza tarjetas, crea vistas específicas y monitorea lo que realmente importa."
      }
    },
    {
      title: {
        en: "Real-time indicators",
        es: "Indicadores en tiempo real"
      },
      description: {
        en: "Visualize sales, traffic, conversions, campaign performance, operational statuses and trends without waiting for manual reports or external consolidations.",
        es: "Visualiza ventas, tráfico, conversiones, desempeño de campañas, estados operativos y tendencias sin esperar reportes manuales ni consolidaciones externas."
      }
    },
    {
      title: {
        en: "Automatic analysis with OS Copilot",
        es: "Análisis automáticos con OS Copilot"
      },
      description: {
        en: "OS Copilot interprets your data, detects patterns, identifies opportunities and generates automatic conclusions that simplify decision-making.",
        es: "OS Copilot interpreta tus datos, detecta patrones, identifica oportunidades y genera conclusiones automáticas que simplifican la toma de decisiones."
      }
    }
  ];

  const results = [
    {
      value: "70%",
      label: {
        en: "faster speed in reading and understanding key metrics",
        es: "más velocidad en la lectura y comprensión de métricas clave"
      }
    },
    {
      value: "50%",
      label: {
        en: "reduction in manual reports generated by teams",
        es: "reducción en reportes manuales generados por los equipos"
      }
    },
    {
      value: "30%",
      label: {
        en: "improvement in tactical decisions thanks to centralized data",
        es: "mejora en decisiones tácticas gracias a datos centralizados"
      }
    }
  ];

  const faqs = [
    {
      question: {
        en: "Can I completely customize my dashboards?",
        es: "¿Puedo personalizar completamente mis dashboards?"
      },
      answer: {
        en: "Yes. You can choose metrics, reorganize cards, create specific views for areas and adjust each panel to your business needs.",
        es: "Sí. Puedes elegir métricas, reorganizar tarjetas, crear vistas específicas para áreas y ajustar cada panel a las necesidades de tu negocio."
      }
    },
    {
      question: {
        en: "What type of data can I connect?",
        es: "¿Qué tipo de datos puedo conectar?"
      },
      answer: {
        en: "Website, digital advertising, inventories, CRM, ERP, payment gateways, campaigns, logistics and any tool that is part of your ecommerce ecosystem.",
        es: "Sitio web, pauta digital, inventarios, CRM, ERP, pasarelas de pago, campañas, logística y cualquier herramienta que forme parte de tu ecosistema de ecommerce."
      }
    },
    {
      question: {
        en: "Do dashboards update in real time?",
        es: "¿Los dashboards se actualizan en tiempo real?"
      },
      answer: {
        en: "Yes. All information is automatically synchronized so your decisions are based on updated and reliable data.",
        es: "Sí. Toda la información se sincroniza automáticamente para que tus decisiones se basen en datos actualizados y confiables."
      }
    }
  ];

  return (
    <>
      <ProductHero {...heroContent} />
      <StatementCards statements={statements} />
      <ResultCards results={results} />
      <ProductFAQ faqs={faqs} />
    </>
  );
}

